server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://ec2-52-0-235-75.compute-1.amazonaws.com:3306/db_candidate
    username: paul
    password: paul23
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate.ddl-auto : update
  main:
    allow-bean-definition-overriding: true
jwt:
  secret: "SECRET-KEY-UNIQUE-GENERATE"
  expiration: 900000
flyway:
  logging:
    level: INFO
  enabled: true
  locations: classpath:db/migration
  baselineOnMigrate: true